project:
  type: website
  output-dir: docs

website:
  title: "UAV projects"
  description: "Innovalab and use the drone for disease infeccious mapping"
  site-url: https://innovala.github.io/uavproject
  twitter-card: true
  favicon: favicon.png
  navbar:
    right:
      - icon: github
        href: https://github.com/innovalav
      - icon: twitter
        href:  https://github.com/innovalav
format:
  html:
    theme: cosmo
    max-width: 600px
    css: styles.css
